on:
  push:
    branches: [main]
jobs:
  deploy-to-server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Build docker image
        run: docker build -t our-home-client:latest .
      - name: Stop and remove existing container
        run: |
          docker stop our-home-client || true
          docker rm our-home-client || true
      - name: Run new container
        run: docker run -d -p 3000:3000 --name our-home-client our-home-client:latest
